import express from 'express';
import multer from 'multer';
import path from 'path';
import fs from 'fs';
import { analyze, refactor, astSummary } from '../core';

const app = express();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 2 * 1024 * 1024 } });
app.use(express.json({ limit: '2mb' }));
const publicDirectory = path.join(__dirname, 'public');
app.use(express.static(publicDirectory));
app.get('/', (_req, res) => res.sendFile(path.join(publicDirectory, 'index.html')));

function analyzeOne(filename: string, code: string) { const result = analyze(code, filename); return { filename, ...result, ast: astSummary(result.ast as any) }; }
app.get('/api/health', (_req, res) => res.json({ ok: true, service: 'ast-green-code-engine' }));
app.post('/api/analyze', (req, res) => { try { const { code, filename = 'source.ts' } = req.body; if (typeof code !== 'string' || code.length > 2_000_000) return res.status(400).json({ error: 'A source string under 2 MB is required.' }); res.json(analyzeOne(filename, code)); } catch (error: any) { res.status(422).json({ error: `Syntax validation failed: ${error.message}` }); } });
app.post('/api/refactor', (req, res) => { try { const { code, filename = 'source.ts' } = req.body; if (typeof code !== 'string') return res.status(400).json({ error: 'A source string is required.' }); const before = analyzeOne(filename, code); const after = refactor(code, filename); res.json({ filename, before, after: { ...after, ast: astSummary(after.ast as any) }, changed: after.code !== code }); } catch (error: any) { res.status(422).json({ error: `Syntax validation failed: ${error.message}` }); } });
app.post('/api/upload', upload.single('file'), async (req, res) => { try { if (!req.file) return res.status(400).json({ error: 'Upload a JavaScript, TypeScript, or ZIP file.' }); const name = req.file.originalname; if (name.toLowerCase().endsWith('.zip')) { const unzipper = await import('unzipper'); const directory = await unzipper.Open.buffer(req.file.buffer); const files = directory.files.filter((f: any) => /\.(js|jsx|ts|tsx)$/.test(f.path) && !f.path.includes('node_modules')).slice(0, 50); const results = []; for (const file of files) results.push(analyzeOne(file.path, (await file.buffer()).toString('utf8'))); return res.json({ filename: name, files: results, findings: results.flatMap(r => r.findings), score: results.length ? Math.round(results.reduce((n, r) => n + r.score, 0) / results.length) : 100 }); } const code = req.file.buffer.toString('utf8'); res.json(analyzeOne(name, code)); } catch (error: any) { res.status(422).json({ error: `Upload processing failed: ${error.message}` }); } });
app.post('/api/benchmark', async (req, res) => { const { code = '', scenario = 'default' } = req.body; const started = Date.now(); try { const puppeteer = require('puppeteer'); const launchOptions: any = process.platform === 'win32' ? { headless: true } : { headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] }; if (process.env.PUPPETEER_EXECUTABLE_PATH) launchOptions.executablePath = process.env.PUPPETEER_EXECUTABLE_PATH; const browser = await puppeteer.launch(launchOptions); const page = await browser.newPage(); const metrics: any[] = []; await page.evaluateOnNewDocument(() => { (window as any).__greenMetrics = { layouts: 0 }; }); await page.setContent(`<script>${String(code).replace(/<\//g, '<\\/')}</script>`); const client = await page.target().createCDPSession(); await client.send('Performance.enable'); const snapshot = await client.send('Performance.getMetrics'); const lookup = (name: string) => (snapshot.metrics as any[]).find(m => m.name === name)?.value ?? 0; metrics.push({ scenario, cpuMainThreadMs: Math.round(lookup('TaskDuration') * 1000), jsHeapMb: Math.round(lookup('JSHeapUsedSize') / 1024 / 1024 * 100) / 100, domLayoutCount: lookup('LayoutCount'), wallTimeMs: Date.now() - started }); await browser.close(); res.json({ metrics }); } catch (error: any) { res.json({ metrics: [{ scenario, cpuMainThreadMs: 0, jsHeapMb: 0, domLayoutCount: 0, wallTimeMs: Date.now() - started }], note: `Puppeteer could not launch Chromium (${error.message || 'unknown error'}). Set PUPPETEER_EXECUTABLE_PATH to a valid Chrome/Chromium executable.` }); } });
const port = Number(process.env.PORT || 4173);
if (require.main === module) app.listen(port, '0.0.0.0', () => console.log(`AST Green-Code dashboard listening on ${port}`));
export default app;
